### ISSUE TITLE
BLOCKING: we need to settle the `v()` signature

### ISSUE THREAD

**Issue by CreaturesInUnitards** [vellajs/vella#16]
Separate from the Godref discussion, we still haven't officially landed:
```js
v(sel|cmp, attrs|attrs?, ...children?)
```
The key question being whether or not attrs are required. If I understand correctly, the blocker with allowing optional attrs is tied to them possibly being a live zone.

If that's the case, I don't believe having the option of wrapping attrs in a function is compelling enough to make attrs required. Others may disagree; regardless we need to nail this down ASAP, so if there is a debate to be had, we need to have if sooner than later.

The hyperscript test suite can't get written, and meaningful POC apps can't—and won't—get written until the signature is stable. We need to push this through.

**Comment by barneycarroll** [comment]
I think it's more the fact that even after recursively [flattening, computing, inspecting] the second argument, it could resolve as a nullish value at any given time… Which as I understand it is fine in an idempotent scenario (if its settled value is stringy, or a node / range: then it's the first child — no attributes; otherwise, it's a nullish or object entity representing attributes)… But I sense this could cause issues if the settled outcome changes over time: if nullish in render 1 becomes a node in render 2, is that node prepended? What if on render 3 it becomes an attribute expression? I feel you'd then remove the node and render the attributes. I _feel_ that, but I also feel unsafe, like this is a lot of inference logic to cater for a highly ambiguous signature. I also feel that any situation where this resolution defies intent points to a "well don't do _that _ then", but the amount of overload afforded to `attrs` expressions is too ambiguous for me to really grok. I guess I still don't understand the use case for computations that resolve to attribute objects, which prevents me from making any educated call on whether the outcomes would be satisfactory to an author who wanted that functionality.

**Comment by foxdonut** [comment]
Having used libs with optional attrs, putting `{}` everywhere got annoying to me. However, I think I could get used to it. I think that is minor, compared to the complexity involved, for the user, for the library, and for our docs, of having optional attrs -- needing a wrapper function, a lambda, etc.

If we have required attrs, the docs can simple be "attrs are required" and the library will be simpler. We could always have a "why are attrs required?" explanation deeper down in the docs, for users who want the full details.

**Comment by foxdonut** [comment]
I'm not very familiar with the possible use cases involving dynamic attrs and attrs being a function.

To me it's either:

A) we can require attrs to be an object without losing any possible functionality, which makes attrs unambiguous, which means attrs are optional. This would be my preference.

B) we must allow attrs to be a function, otherwise we lose possible functionality, or we make implementing that functionality, tedious. This makes optional attrs ambiguous. If that's the case, I'd vote for attrs to be required.

**Comment by foxdonut** [comment]
Well, only crazy people never change their mind :)

What if we made attrs optional, and assumed that with 2 arguments:
- if the second argument is an object, it is attrs
- else, it is a child

In that case, the only problem is if we want 2 arguments, with a non-object attrs as the second argument.

- `v(sel, children)`
- `v(sel, attrsObject)`
- `v(sel, attrsObject, children)`
- `v(sel, attrsFnStreamArrEtc, children)`
- `v(sel, a(attrsFnStreamArrEtc))`

Am I missing something?

**Comment by CreaturesInUnitards** [comment]
@foxdonut actually, I realized after the fact that yes, there's one problem with your list.
If the 1st is possible, the 4th is not.

**Comment by foxdonut** [comment]
@CreaturesInUnitards good point. so then it becomes always wrapping `attrsFnStreamArrEtc` in `a()`:

- `v(sel, children)`
- `v(sel, attrsObject)`
- `v(sel, attrsObject, children)`
- `v(sel, a(attrsFnStreamArrEtc), children)`
- `v(sel, a(attrsFnStreamArrEtc))`

I'm still thinking that the relative infrequency of `attrsFnStreamArrEtc` makes this acceptable.

**Comment by barneycarroll** [comment]
There's an idea for v invocations to keep returning functions with each successive invocation denoting a different part of the view expression. It gets around the variadic arguments problem by allowing closing and reopening parentheses as delimiters. The simple proposal is:

#### 1st call qualifies the DOM element or component: `v(tag, ...attrs?)`
Attributes can be as overloaded as we like, since everything post tag in the initial function call is understood to be part of an attribute expression.

#### 2nd call, if desired, supplies children: `v(...)(...children?)`
I think these are pretty simple and legible, they nerf the ambiguity problem and the attendent desire for a special named API for attribute expressions, and allow us to consider the proposed complexity of attribute expressions on their own merit. One of the really neat things here IMO is that we avoid having to name things or parse too many square brackets or functions, it's nice and contained. Then there's a controversial extension of the proposal for hooks:

#### 3rd call, if desired, supplies hooks: `v(...)(...)(...effects)`
Dom Ganaway last I heard was working on idioms for React to become its own DSL that superceded DOM idioms and posited event listeners as hierarchical nodes rather than properties of other nodes which makes a lot of sense to me. This is similar but rather than overriding DOM conventions we're saying no more special casing attributes / properties or components for framework concerns, and furthermore, again, saves us from having to name things. Further furthermore it enables all the same freedom of expression accorded to attribute and children expressions to bring to bear on lifecycle. I think I originally suggested this in Mithril Gitter, and my idea then was for effects to take the form of:

```
(...domNodes) => {
  // on render
  // ...and, optionally:
  return () => {
    // on teardown
    // ...and, optionally:
    return promise 
  } 
}
```
I kicked that last bit about with Rasmus Porsager a fair bit and we were pretty pleased about it.

**Comment by CreaturesInUnitards** [comment]
_Maaaaaannnn...._ I don't know about that, @barneycarroll. I realize that it solves the polymorphic issues we're encountering, but if that means that composition/partial application are to be central to how vella views are constructed... I think that could relegate vella to being the Haskell of FE frameworks.

Betamax, even.

I have no doubts about the technical feasibility. I think it's brilliant, and could be compelling for advanced use cases. But `v` should be vella's door handle; it shouldn't be its manual transmission. IMHO the ergonomics are _far_ too advanced for genpop.

**Comment by foxdonut** [comment]
@barneycarroll that's a really interesting proposal!

But... it would turn this:

```javascript
v('div', {class: 'wrapper', style: hexifyForCSS(colors)},
  colors.map(channel => v('div', {class: 'color_channel'},
    v('span', channel.name),
    v('div', {class: "chip", style: rgbColor(channel)}),
    v('div', {class: 'button_wrapper'},
      v('span', {class: 'button', onclick(){channel.inc(-1)}}, '-'),
      v('span', {class: 'button', onclick(){channel.inc(1)}}, '+')
    ),
    v('span', {class: 'decimal'}, channel.value)
  )),
  v('span', "HEX value: ", hexifyForDOM(colors))
)
```

into this:

```javascript
v('div', {class: 'wrapper', style: hexifyForCSS(colors)})(
  colors.map(channel => v('div', {class: 'color_channel'})(
    v('span')(channel.name),
    v('div', {class: "chip", style: rgbColor(channel)}),
    v('div', {class: 'button_wrapper'})(
      v('span', {class: 'button', onclick(){channel.inc(-1)}})('-'),
      v('span', {class: 'button', onclick(){channel.inc(1)}})('+')
    ),
    v('span', {class: 'decimal'})(channel.value)
  )),
  v('span')("HEX value: ", hexifyForDOM(colors))
)

I agree with @CreaturesInUnitards , I think it's brilliant but it puts complexity at every call to `v` for solving much less frequent use cases (stream attrs, animation hooks).

@pygy also mentioned that it would have a performance cost.

I just don't like the idea of having to explain on page 1, "you have to write `v('div')('text')`..." and then, to explain why, "um, because of attrs ambiguity if you use a stream or a lambda..."

On the other hand, the use of `v.a(...)` to wrap would be _only_ if you use a stream or a lambda for attrs, which is far less frequent, and thus would not be on page 1 of `vella`. A particular case for a particular case.

**Comment by pygy** [comment]
It should be noted that optinal attrs `v(selector, attrs?, ...children)` are perf considerations, even if we prohibit streams in attrs position. Telling apart a Node from a POJO (`x != null && typeof x === "object" && x instanceof Node`) requires a 4 level prototype lookup for elements without attrs `v('', x)`, where `x` is a node. We could restrict children to elements (prohibit passing text nodes and comments as children, only three prototypes lookups) but that would make `v.trust` more complex to write when fragments are involved (since we'd have to turn text nodes back to text, and ditch comments, or say they are not supported).

**Comment by pygy** [comment]
So there's either going to be a perf cost with a single `v()` (regardless of #21 the prototype lookup and the TTL/curried solutions all have overhead... Mithril looks for and own `tag` as the `vnode` discriminant, which is fast and doesn't allocate), and/or a papercut of some kind...

Either:
- mandatory attrs? Annoying because 
- an extra name to refer to:

```JS
import {v, vc} from 'vella'
// or
const {vc} = v
// or
v.vc(tag, ...children)
```

```JS
import {v, a} from 'vella'
// or
const {a} = v
// or 
v(tag, v.a(attrs), ...children)
```

both vc and v.a can be made fast (vc being the fastest).

@barneycarroll I'd like the dom hooks to apply to both nodes and dynamic fragments, with the same syntax (having both `Ref` and `Refs` components is as far as I'd go).

**Comment by spacejack** [comment]
My thoughts are, if vella redraws are so precise and granular, is the 4-level prototype test anything to worry about?

Also... ideally it should be benchmarked to confirm that `instanceof Node` is as expensive as you're assuming.

**Comment by pygy** [comment]
> My thoughts are, if vella redraws are so precise and granular, is the 4-level prototype test anything to worry about?

I'd also tend to lean that way. The potential problem is initial render perf. It can be mitigated by SSR and hydration, but it isn't always possible, and the tooling overhead is non-negligible. Pre-compilation (Solid-like) is also possible, but I don't know if it even improves the initial rendering times, because the nodes have to be allocated twice (once in the template, and once when it is cloned).

If we make attrs mandatory, we could use `v` as a placeholder for empty attrs.

```JS
v('.foo', v, v('.bar'))
```

It's easier to type than either `{}` or `null`, it doesn't allocate, and it is fast to check. I isn't wonderful visually, but it isn't bad either.

**Comment by leeoniya** [comment]
> It's easier to type than either {} or null, it doesn't allocate, and it is fast to check. I isn't wonderful visually, but it isn't bad either.

ivi uses an exported `_` which is less odd than reusing `v`, imo.

https://github.com/localvoid/ivi

**Comment by pygy** [comment]
I agree it looks better, but the name clash with lodash is unfortunate...

**Comment by pygy** [comment]
I'll write benchmarks of the various signature possibilities this evening to get concrete data.
